# One Hot Encoder / Norminal Encoder

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.read_csv('/content/drive/MyDrive/Feature Engineering and ETA/HousePrice_AdvRegressionTechnique/train.csv')
df.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [6]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [7]:
df["LotShape"].value_counts()

LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

Here we will be using LotShape column data to check how One hot encodding is used.

In [9]:
encoder=OneHotEncoder()
encoder_val=encoder.fit_transform(df[["LotShape"]]).toarray()

In [10]:
encoded_df=pd.DataFrame(encoder_val,columns=encoder.get_feature_names_out())

In [11]:
encoded_df.head()

   LotShape_IR1  LotShape_IR2  LotShape_IR3  LotShape_Reg
0           0.0           0.0           0.0           1.0
1           0.0           0.0           0.0           1.0
2           1.0           0.0           0.0           0.0
3           1.0           0.0           0.0           0.0
4           1.0           0.0           0.0           0.0

In [16]:
pd.concat([df['LotShape'],encoded_df],axis=1)

     LotShape  LotShape_IR1  LotShape_IR2  LotShape_IR3  LotShape_Reg
0         Reg           0.0           0.0           0.0           1.0
1         Reg           0.0           0.0           0.0           1.0
2         IR1           1.0           0.0           0.0           0.0
3         IR1           1.0           0.0           0.0           0.0
4         IR1           1.0           0.0           0.0           0.0
...       ...           ...           ...           ...           ...
1455      Reg           0.0           0.0           0.0           1.0
1456      Reg           0.0           0.0           0.0           1.0
1457      Reg           0.0           0.0           0.0           1.0
1458      Reg           0.0           0.0           0.0           1.0
1459      Reg           0.0           0.0           0.0           1.0

[1460 rows x 5 columns]

If we get any new feature we need to convert it into sparks matrix.

In [12]:
encoder.transform([["IR1"]]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 0.]])